language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mooc' ]; then cd .. && eval "mv $currentfolder generator-mooc" && cd generator-mooc; fi
